version: '3.7'
services:
        account-service:
                image: alinawazmamdani/account-service:${BUILD_NUMBER}
                build: ./account-service
                depends_on:
                        - mongo-service
                        - secret-service
        aes-encryption-service:
                image: alinawazmamdani/aes-encryption-service:${BUILD_NUMBER}
                build: ./aes-encryption-service
        authentication-client:
                image: alinawazmamdani/authentication-client:${BUILD_NUMBER}
                build: ./authentication-client
        authentication-service:
                image: alinawazmamdani/authentication-service:${BUILD_NUMBER}
                build: ./authentication-service
                environment:
                        - ACTIVATION_LINK=http://${ACTIVATION_IP}/authentication/api/activate
        dashboard-client:
                image: alinawazmamdani/dashboard-client:${BUILD_NUMBER} 
                build: ./dashboard-client
        dashboard-service:
                image: alinawazmamdani/dashboard-service:${BUILD_NUMBER} 
                build: ./dashboard-service
                depends_on:
                        - account-service
                        - session-token-service
        email-service: 
                image: alinawazmamdani/email-service:${BUILD_NUMBER} 
                build: ./email-service
                depends_on:
                        - aes-encryption-service
                environment:
                        - GMAIL_USER=ilovedocker123@gmail.com
                        - GMAIL_PASS=ilovedocker1!
                        - SERVICE_NAME="CI project"

        gateway: 
                image: alinawazmamdani/gateway:${BUILD_NUMBER} 
                build: ./gateway
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp
                depends_on:
                        - dashboard-client
                        - authentication-client
                        - authentication-service
                        - dashboard-service
        group-service: 
                image: alinawazmamdani/group-service:${BUILD_NUMBER} 
                build: ./group-service
        mongo-service: 
                image: alinawazmamdani/mongo-service:${BUILD_NUMBER}  
                build: ./mongo-service
                depends_on:
                        - mongo
        role-service: 
                image: alinawazmamdani/role-service:${BUILD_NUMBER}
                build: ./role-service
        secret-service: 
                image: alinawazmamdani/secret-service:${BUILD_NUMBER} 
                build: ./secret-service
                depends_on:
                        - mongo-service
        session-token-service: 
                image: alinawazmamdani/session-token-service:${BUILD_NUMBER} 
                build: ./session-token-service
                depends_on:
                        - mongo-service
                        - aes-encryption-service
        mongo:
                image: mongo 



